
import type { Product } from './products';
import type { User } from './users';
import type { Settings } from './settings';


export const initialProductsData: Omit<Product, 'id'>[] = [
  {
    nombre: 'CERTIFICADO COMERCIAL',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'CERTIFICADOS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'FOTOCOPIA B/N',
    precio: 300,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'IMPRESIONES',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'FOTOCOPIA COLOR',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'IMPRESIONES',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'IMPRESION FOTO 10x15',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'IMPRESIONES',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'IMPRESION CARTA B/N',
    precio: 500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'IMPRESIONES',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'IMPRESION OFICIO B/N',
    precio: 600,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'IMPRESIONES',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'IMPRESION CARTA COLOR',
    precio: 1500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'IMPRESIONES',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'IMPRESION OFICIO COLOR',
    precio: 1800,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'IMPRESIONES',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'ESCANER',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'SERVICIOS DIGITALES',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'AFILIACION SEGURIDAD SOCIAL',
    precio: 10000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'SERVICIOS DIGITALES',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'AGENDA WEB',
    precio: 5000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'SERVICIOS DIGITALES',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'CERTIFICADO ANTECEDENTES',
    precio: 3000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'CERTIFICADOS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'CERTIFICADO PROCURADURIA',
    precio: 3000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'CERTIFICADOS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'CERTIFICADO CONTRALORIA',
    precio: 3000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'CERTIFICADOS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'CERTIFICADO REGISTRO CIVIL',
    precio: 10000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'CERTIFICADOS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'CERTIFICADO TRADICION',
    precio: 25000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'CERTIFICADOS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'RUT',
    precio: 8000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'DOCUMENTOS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'CURVA SISBEN',
    precio: 5000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'DOCUMENTOS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'RECIBO DE CAFE',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'DOCUMENTOS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'LAMINACION',
    precio: 2500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'ARGollado',
    precio: 5000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'CURRICULUM',
    precio: 5000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'DOCUMENTOS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'TRAMITE ASOPAGOS',
    precio: 5000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'SERVICIOS DIGITALES',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'RECARGA MOVIL',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'RECARGAS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'PAQUETE MOVIL',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'RECARGAS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'SOAT',
    precio: 0,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'SEGUROS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'SEGURO MOTO',
    precio: 0,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'SEGUROS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'SEGURO CARRO',
    precio: 0,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'SEGUROS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'HISTORIAL LICENCIA',
    precio: 5000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'DOCUMENTOS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'CITA INE',
    precio: 5000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'SERVICIOS DIGITALES',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'APUESTAS DEPORTIVAS',
    precio: 0,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'APUESTAS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'CHANCE',
    precio: 0,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'APUESTAS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'LOTERIA',
    precio: 0,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'APUESTAS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'RIFAS',
    precio: 0,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'APUESTAS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Pago de Facturas',
    precio: 0,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAGOS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Envio de Giros',
    precio: 0,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'GIROS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Retiro de Giros',
    precio: 0,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'GIROS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Simcard',
    precio: 3000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'RECARGAS',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Lapiceros',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Borrador',
    precio: 500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Tajalapiz',
    precio: 500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Cartulina',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Papel seda',
    precio: 500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Silicona',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Pegante',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Sobre de manila',
    precio: 500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Carpeta',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Legajador',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Tijeras',
    precio: 1500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Corrector',
    precio: 1500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Marcadores',
    precio: 1500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Colores',
    precio: 3000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Regla',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Pincel',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Vinilos',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Ganchos',
    precio: 500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Cosedora',
    precio: 5000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Perforadora',
    precio: 5000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Block',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Cuaderno',
    precio: 3000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Papel contact',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Papel crepe',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Papel globo',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Papel periodico',
    precio: 500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Cinta',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Bisturi',
    precio: 1500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'PAPELERIA',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Gel Antibacterial',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'ASEO',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Alcohol',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'ASEO',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Tapabocas',
    precio: 1000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'ASEO',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Pañitos humedos',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'ASEO',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Toallas higienicas',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'ASEO',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Crema dental',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'ASEO',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Cepillo dental',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'ASEO',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Jabon de baño',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'ASEO',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Shampoo',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'ASEO',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Acondicionador',
    precio: 2000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'ASEO',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Desodorante',
    precio: 5000,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'ASEO',
    imagen: 'https://placehold.co/600x400.png',
  },
  {
    nombre: 'Papel higienico',
    precio: 1500,
    existencias: 100,
    disponibilidad: 'PRODUCTO_DISPONIBLE',
    categoria: 'ASEO',
    imagen: 'https://placehold.co/600x400.png',
  },
];

export const initialUsersData: User[] = [
  {
    id: 1,
    name: 'Admin Principal',
    email: 'admin@example.com',
    password: 'admin123',
    role: 'admin',
    temporaryPassword: false
  },
  {
    id: 2,
    name: 'Juan Mesero',
    email: 'mesero@example.com',
    cedula: '10203040',
    password: '10203040', // Cedula is the password
    role: 'waiter',
    temporaryPassword: false
  },
];

export const initialSettings: Settings = {
  barName: 'HOLIDAYS FRIENDS',
  logoUrl: 'https://storage.googleapis.com/project-spark-b6b15e45/c015b678-9e5c-4467-8566-3c0a4c079237.png',
  backgroundUrl: 'https://storage.googleapis.com/project-spark-b6b15e45/dc407172-5953-4565-a83a-48a58ca7694f.png',
  promotionalImages: [
      { id: 1, src: "https://storage.googleapis.com/project-spark-b6b15e45/c015b678-9e5c-4467-8566-3c0a4c079237.png", alt: "Promoción 1", hint: "promotion event" },
      { id: 2, src: "https://storage.googleapis.com/project-spark-b6b15e45/f8365f57-631d-4475-a083-207d5781a7b4.png", alt: "Promoción 2", hint: "special offer" },
      { id: 3, src: "https://storage.googleapis.com/project-spark-b6b15e45/dc407172-5953-4565-a83a-48a58ca7694f.png", alt: "Promoción 3", hint: "discount party" },
      { id: 4, src: "https://storage.googleapis.com/project-spark-b6b15e45/05459f37-64cd-4e89-9a7c-1795c6439167.png", alt: "Promoción 4", hint: "happy hour" },
  ]
};
