import type {NextConfig} from 'next';

const nextConfig: NextConfig = {
  /* config options here */
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'placehold.co',
      },
      {
        protocol: 'https',
        hostname: 'storage.googleapis.com',
      },
      { protocol: 'https', hostname: 'avatars.mds.yandex.net' },
      { protocol: 'https', hostname: 'images.squarespace-cdn.com' },
      { protocol: 'https', hostname: 'i.pinimg.com' },
      { protocol: 'https', hostname: 'us-tuna-sounds-images.voicemod.net' },
      { protocol: 'https', hostname: 'jumbocolombiafood.vteximg.com.br' },
      { protocol: 'https', hostname: 'cdn2.yopongoelhielo.com' },
      { protocol: 'https', hostname: 'lavaquita.co' },
      { protocol: 'https', hostname: 'www.totalwine.com' },
      { protocol: 'https', hostname: 'elcorreodelanoche.com.co' },
      { protocol: 'https', hostname: 'licoreselcastillo.com.co' },
      { protocol: 'https', hostname: 'carulla.vtexassets.com' },
      { protocol: 'https', hostname: 'exitocol.vtexassets.com' },
      { protocol: 'https', hostname: 'image.winudf.com' },
      { protocol: 'https', hostname: 'images.genius.com' },
      { protocol: 'https', hostname: 'dislicores.vteximg.com.br' },
      { protocol: 'https', hostname: 'www.pngkit.com' },
      { protocol: 'https', hostname: 'www.pngkey.com' },
      { protocol: 'https', hostname: 'www.pngfind.com' },
      { protocol: 'https', hostname: 'i.ytimg.com' },
      { protocol: 'https', hostname: 'ziliottigroup.it' },
      { protocol: 'https', hostname: 'images-eu.ssl-images-amazon.com' },
      { protocol: 'https', hostname: 'image.pngaaa.com' },
      { protocol: 'https', hostname: 'main-cdn.sbermegamarket.ru' },
      { protocol: 'https', hostname: 'www.zirus.pizza' },
      { protocol: 'https', hostname: 'www.bavaria.co' },
      { protocol: 'https', hostname: 'koyotebarbacoa.com' },
      { protocol: 'https', hostname: 'mir-s3-cdn-cf.behance.net' },
      { protocol: 'https', hostname: 'static.insales-cdn.com' },
      { protocol: 'https', hostname: 'upload.wikimedia.org' },
      { protocol: 'https', hostname: 'www.tapintoyourbeer.com' },
      { protocol: 'https', hostname: 'mambodelivery.vtexassets.com' },
      { protocol: 'https', hostname: 'cdn.forbes.co' },
      { protocol: 'https', hostname: 'i3.wp.com' },
      { protocol: 'https', hostname: 'resources.claroshop.com' },
      { protocol: 'https', hostname: 'e7.pngegg.com' },
      { protocol: 'https', hostname: 'imageproxy.wolt.com' },
      { protocol: 'https', hostname: 'cdn.100sp.ru' },
      { protocol: 'https', hostname: 'www.smartuk.net' },
      { protocol: 'https', hostname: 'www.nicepng.com' },
      { protocol: 'https', hostname: 'userscontent2.emaze.com' },
      { protocol: 'https', hostname: 'parce.ca' },
      { protocol: 'https', hostname: 'usabrother.com' },
      { protocol: 'https', hostname: 'supermercadocomunal.com' },
      { protocol: 'https', hostname: 'cdn1.ozone.ru' },
      { protocol: 'https', hostname: 'dw95zbr0bn7mn.cloudfront.net' },
      { protocol: 'https', hostname: 'vkuster.ru' },
      { protocol: 'https', hostname: 'winehelp2.ru' },
      { protocol: 'https', hostname: 'www.static-src.com' },
      { protocol: 'https', hostname: 'licoresquindio.com' },
      { protocol: 'https', hostname: 'kyva.co' },
      { protocol: 'https', hostname: 'www.sultanatesi.com.tr' },
      { protocol: 'https', hostname: 'applejack.com' },
      { protocol: 'https', hostname: 's.alicdn.com' },
      { protocol: 'https', hostname: 'www.bottiglieriadelmassimo.it' },
      { protocol: 'https', hostname: 'batavialiquor.com' },
      { protocol: 'https', hostname: 'm.media-amazon.com' },
      { protocol: 'https', hostname: 'www.vitacost.com' },
      { protocol: 'https', hostname: 'cs13.pikabu.ru' },
      { protocol: 'https', hostname: 'i5.walmartimages.com' },
      { protocol: 'https', hostname: 'vivanda.vteximg.com.br' },
      { protocol: 'https', hostname: 'whiskyworld.ru' },
      { protocol: 'https', hostname: 'regstaer.ru' },
      { protocol: 'https', hostname: 'www.naughtygrapett.com' },
      { protocol: 'https', hostname: 'drinkcentral.co' },
    ],
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
};

export default nextConfig;
